apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    kubernetes:
      envoyDeployment:
        pod:
          nodeSelector:
            cloud.ionos.com/nodepool-name: loadbalancer
      envoyService:
        annotations:
          cloud.ionos.com/node-selector: cloud.ionos.com/nodepool-name=loadbalancer
        externalTrafficPolicy: Local
        type: LoadBalancer
    type: Kubernetes


